import { GoogleGenAI, Type } from "@google/genai";

const GEMINI_API_KEY = process.env.GEMINI_API_KEY;

export interface AnalysisResult {
  ai_probability: number;
  risk_level: "Low" | "Medium" | "High";
  confidence: "Low" | "Medium" | "High";
  reasons: string[];
  analysis_summary?: string;
  artifact_score?: number;
  lighting_score?: number;
  realism_score?: number;
  linguistic_score?: number;
  structure_score?: number;
  genericness_score?: number;
  // Video specific
  frame_artifact_score?: number;
  temporal_score?: number;
  expert_panel?: {
    artifact_detector: string;
    lighting_analyst: string;
    ai_judge: string;
  };
}

export async function analyzeText(text: string): Promise<AnalysisResult> {
  if (!GEMINI_API_KEY) {
    throw new Error("Gemini API key is not configured.");
  }

  const ai = new GoogleGenAI({ apiKey: GEMINI_API_KEY });
  
  const response = await ai.models.generateContent({
    model: "gemini-3-flash-preview",
    contents: `You are an AI forensic linguistic analyst system composed of:

1) Linguistic Analyst – evaluates naturalness, vocabulary, and emotional nuance.
2) Pattern Specialist – checks for repetitive structures and machine-like consistency.
3) AI Judge – provides the final forensic verdict.

Your task is to analyze the given text and estimate the probability (0–100%) that it was generated by an AI system.

Base your evaluation on:
- Generic or broadly applicable statements
- Lack of personal experience or specific details
- Overly balanced or structured tone
- Repetitive sentence structure
- Common AI phrases (e.g., “vast datasets”, “remarkable speed”, “responsible implementation”)
- Formal, neutral, or polished academic style
- Absence of emotional variation or idiosyncratic phrasing

Scoring rules:
0–30 → Low
31–60 → Medium
61–100 → High

Now analyze this text:
"""
${text}
"""`,
    config: {
      systemInstruction: "You are an expert AI forensic linguistic analyst system. Your task is to provide a highly accurate estimation of whether a text was written by a human or an AI. You must return ONLY a JSON object following the specified schema.",
      responseMimeType: "application/json",
      responseSchema: {
        type: Type.OBJECT,
        properties: {
          ai_probability: { type: Type.NUMBER },
          risk_level: { type: Type.STRING, enum: ["Low", "Medium", "High"] },
          confidence: { type: Type.STRING, enum: ["Low", "Medium", "High"] },
          linguistic_score: { type: Type.NUMBER, description: "Score for linguistic naturalness (0-100)" },
          structure_score: { type: Type.NUMBER, description: "Score for structural complexity (0-100)" },
          genericness_score: { type: Type.NUMBER, description: "Score for how generic the content is (0-100)" },
          expert_panel: {
            type: Type.OBJECT,
            properties: {
              artifact_detector: { type: Type.STRING, description: "Linguistic Analyst verdict" },
              lighting_analyst: { type: Type.STRING, description: "Pattern Specialist verdict" },
              ai_judge: { type: Type.STRING, description: "AI Judge final verdict" },
            },
            required: ["artifact_detector", "lighting_analyst", "ai_judge"],
          },
          reasons: {
            type: Type.ARRAY,
            items: { type: Type.STRING },
          },
        },
        required: ["ai_probability", "risk_level", "confidence", "linguistic_score", "structure_score", "genericness_score", "expert_panel", "reasons"],
      },
    },
  });

  try {
    const result = JSON.parse(response.text || "{}");
    return result as AnalysisResult;
  } catch (error) {
    console.error("Failed to parse AI response:", error);
    throw new Error("The analysis failed to generate a valid report.");
  }
}

export async function analyzeImage(base64Data: string, mimeType: string): Promise<AnalysisResult> {
  if (!GEMINI_API_KEY) {
    throw new Error("Gemini API key is not configured.");
  }

  const ai = new GoogleGenAI({ apiKey: GEMINI_API_KEY });
  
  const response = await ai.models.generateContent({
    model: "gemini-3-flash-preview",
    contents: {
      parts: [
        {
          inlineData: {
            data: base64Data,
            mimeType: mimeType,
          },
        },
        {
          text: `You are a Digital Image Forensics System composed of:

1) Visual Artifact Detector – checks distortions, texture anomalies, facial inconsistencies.
2) Lighting & Shadow Analyst – evaluates unnatural light distribution.
3) AI Image Judge – provides final probability estimate.

Analyze the provided image and estimate probability (0–100%) that it was generated by AI.

Consider:
- Distorted fingers or facial asymmetry
- Unrealistic smoothness
- Warped backgrounds
- Inconsistent shadows
- Synthetic textures
- Lack of natural noise

SCORING RULES:
0–30 → Low Risk
31–60 → Medium Risk
61–100 → High Risk`,
        },
      ],
    },
    config: {
      systemInstruction: "You are an expert Digital Image Forensics System. Your task is to provide a highly accurate estimation of whether an image was created by a human/camera or an AI. You must return ONLY a JSON object following the specified schema.",
      responseMimeType: "application/json",
      responseSchema: {
        type: Type.OBJECT,
        properties: {
          artifact_score: { type: Type.NUMBER },
          lighting_score: { type: Type.NUMBER },
          realism_score: { type: Type.NUMBER },
          ai_probability: { type: Type.NUMBER },
          risk_level: { type: Type.STRING, enum: ["Low", "Medium", "High"] },
          confidence: { type: Type.STRING, enum: ["Low", "Medium", "High"] },
          expert_panel: {
            type: Type.OBJECT,
            properties: {
              artifact_detector: { type: Type.STRING },
              lighting_analyst: { type: Type.STRING },
              ai_judge: { type: Type.STRING },
            },
            required: ["artifact_detector", "lighting_analyst", "ai_judge"],
          },
          reasons: {
            type: Type.ARRAY,
            items: { type: Type.STRING },
          },
        },
        required: ["artifact_score", "lighting_score", "realism_score", "ai_probability", "risk_level", "confidence", "expert_panel", "reasons"],
      },
    },
  });

  try {
    const result = JSON.parse(response.text || "{}");
    return result as AnalysisResult;
  } catch (error) {
    console.error("Failed to parse AI response:", error);
    throw new Error("The image analysis failed to generate a valid report.");
  }
}

export async function analyzeVideo(base64Frame: string, mimeType: string): Promise<AnalysisResult> {
  if (!GEMINI_API_KEY) {
    throw new Error("Gemini API key is not configured.");
  }

  const ai = new GoogleGenAI({ apiKey: GEMINI_API_KEY });
  
  const response = await ai.models.generateContent({
    model: "gemini-3-flash-preview",
    contents: {
      parts: [
        {
          inlineData: {
            data: base64Frame,
            mimeType: mimeType,
          },
        },
        {
          text: `You are a Video Deepfake Forensic System. Analyze the provided key frame from a video and estimate the probability (0–100%) that the video is AI-generated/deepfaked.
          
          Consider:
          - Facial distortions or "ghosting"
          - Unnatural eye blinking or lip-sync
          - Background warping during motion
          - Lighting inconsistencies across frames
          - Unrealistic skin smoothness
          - Temporal artifacts (jitter, blending)
          
          SCORING RULES:
          0–30 → Low Risk
          31–60 → Medium Risk
          61–100 → High Risk`,
        },
      ],
    },
    config: {
      systemInstruction: "You are an expert Video Deepfake Forensic System. Your task is to provide a highly accurate estimation of whether a video was created by a human or an AI. You must return ONLY a JSON object following the specified schema.",
      responseMimeType: "application/json",
      responseSchema: {
        type: Type.OBJECT,
        properties: {
          frame_artifact_score: { type: Type.NUMBER, description: "Score for visual artifacts in frames (0-100)" },
          temporal_score: { type: Type.NUMBER, description: "Score for temporal/motion consistency (0-100)" },
          realism_score: { type: Type.NUMBER, description: "Score for overall realism (0-100)" },
          ai_probability: { type: Type.NUMBER },
          risk_level: { type: Type.STRING, enum: ["Low", "Medium", "High"] },
          confidence: { type: Type.STRING, enum: ["Low", "Medium", "High"] },
          analysis_summary: { type: Type.STRING },
          reasons: {
            type: Type.ARRAY,
            items: { type: Type.STRING },
          },
        },
        required: ["frame_artifact_score", "temporal_score", "realism_score", "ai_probability", "risk_level", "confidence", "analysis_summary", "reasons"],
      },
    },
  });

  try {
    const result = JSON.parse(response.text || "{}");
    return result as AnalysisResult;
  } catch (error) {
    console.error("Failed to parse AI response:", error);
    throw new Error("The video analysis failed to generate a valid report.");
  }
}
