import { motion } from "motion/react";
import {
  AlertCircle,
  CheckCircle2,
  Info,
  ShieldAlert,
  Fingerprint,
  Activity,
  Zap,
  Eye,
  Download,
  Brain,
  Layout,
  Scale,
  BarChart3
} from "lucide-react";
import type { AnalysisResult } from "../services/gemini";
import { cn } from "../utils/cn";

interface Props {
  result: AnalysisResult;
}

export function AnalysisResultView({ result }: Props) {
  const getRiskColor = (level: string) => {
    switch (level) {
      case "Low": return "text-emerald-400";
      case "Medium": return "text-amber-400";
      case "High": return "text-rose-400";
      default: return "text-zinc-400";
    }
  };

  const getRiskBg = (level: string) => {
    switch (level) {
      case "Low": return "bg-emerald-500/5 border-emerald-500/20";
      case "Medium": return "bg-amber-500/5 border-amber-500/20";
      case "High": return "bg-rose-500/5 border-rose-500/20";
      default: return "bg-zinc-500/5 border-zinc-500/20";
    }
  };

  const getRiskGlow = (level: string) => {
    switch (level) {
      case "Low": return "shadow-[0_0_20px_rgba(16,185,129,0.1)]";
      case "Medium": return "shadow-[0_0_20px_rgba(245,158,11,0.1)]";
      case "High": return "shadow-[0_0_30px_rgba(244,63,94,0.2)]";
      default: return "";
    }
  };

  const getRiskIcon = (level: string) => {
    switch (level) {
      case "Low": return <CheckCircle2 className="w-5 h-5" />;
      case "Medium": return <Info className="w-5 h-5" />;
      case "High": return <ShieldAlert className="w-5 h-5" />;
      default: return <AlertCircle className="w-5 h-5" />;
    }
  };

  const downloadReport = () => {
    const report = `
FORENSIC ANALYSIS REPORT
-------------------------
AI Probability: ${result.ai_probability}%
Risk Level: ${result.risk_level}
Confidence: ${result.confidence}

${result.frame_artifact_score !== undefined ? `
VIDEO FORENSIC SCORES:
- Frame Artifact Score: ${result.frame_artifact_score}/100
- Temporal Consistency: ${result.temporal_score}/100
- Realism Score: ${result.realism_score}/100
` : result.artifact_score !== undefined ? `
IMAGE FORENSIC SCORES:
- Artifact Detector: ${result.artifact_score}/100
- Lighting Analyst: ${result.lighting_score}/100
- Realism Score: ${result.realism_score}/100
` : `
TEXT FORENSIC SCORES:
- Linguistic Naturalness: ${result.linguistic_score}/100
- Structural Complexity: ${result.structure_score}/100
- Content Genericness: ${result.genericness_score}/100
`}

${result.analysis_summary ? `ANALYSIS SUMMARY:\n${result.analysis_summary}\n` : ""}

EXPERT PANEL VERDICTS:
${result.expert_panel ? `
- Artifact Detector: ${result.expert_panel.artifact_detector}
- Lighting Analyst: ${result.expert_panel.lighting_analyst}
- AI Judge: ${result.expert_panel.ai_judge}
` : 'Forensic analysis conducted by AI Forensic Systems.'}

FORENSIC INDICATORS:
${result.reasons.map(r => `- ${r}`).join('\n')}

Generated by AI Investigator
    `.trim();

    const blob = new Blob([report], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `forensic-report-${Date.now()}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      className="space-y-8"
    >
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-3">
          <BarChart3 className="w-4 h-4 text-cyber-blue" />
          <h2 className="text-[10px] font-mono uppercase tracking-[0.3em] text-zinc-500">Forensic Intelligence Output</h2>
        </div>
        <button
          onClick={downloadReport}
          className="px-4 py-2 bg-cyber-blue text-cyber-navy text-[10px] font-mono uppercase font-black tracking-widest hover:shadow-[0_0_20px_rgba(16,185,129,0.3)] transition-all flex items-center gap-2 group shadow-lg"
        >
          <Download className="w-3 h-3 group-hover:translate-y-0.5 transition-transform" />
          Export Report
        </button>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
        {/* Probability Meter */}
        <div className={cn(
          "glass-card rounded-none border-t-2 border-t-cyber-blue p-10 flex flex-col items-center justify-center text-center relative overflow-hidden group transition-all duration-1000",
          result.risk_level === "High" ? "glow-pulse-red border-t-rose-500" : ""
        )}>
          <div className="absolute top-2 left-2 w-2 h-2 border-t border-l border-cyber-blue/30" />
          <div className="absolute top-2 right-2 w-2 h-2 border-t border-r border-cyber-blue/30" />
          <div className="absolute bottom-2 left-2 w-2 h-2 border-b border-l border-cyber-blue/30" />
          <div className="absolute bottom-2 right-2 w-2 h-2 border-b border-r border-cyber-blue/30" />

          <span className="text-[9px] font-mono uppercase tracking-[0.4em] text-zinc-600 mb-8">AI Probability Index</span>

          <div className="relative group">
            <div className="absolute inset-0 bg-cyber-blue/5 rounded-full blur-3xl group-hover:bg-cyber-blue/10 transition-colors" />
            <svg className="w-56 h-56 transform -rotate-90 relative z-10">
              <circle
                cx="112"
                cy="112"
                r="100"
                stroke="currentColor"
                strokeWidth="2"
                fill="transparent"
                className="text-white/5"
              />
              <motion.circle
                cx="112"
                cy="112"
                r="100"
                stroke="currentColor"
                strokeWidth="12"
                fill="transparent"
                strokeDasharray={628.3}
                initial={{ strokeDashoffset: 628.3 }}
                animate={{ strokeDashoffset: 628.3 - (628.3 * result.ai_probability) / 100 }}
                transition={{ duration: 2.5, ease: "circOut", delay: 0.5 }}
                className={cn(
                  "transition-all duration-1000",
                  result.ai_probability > 60 ? "text-rose-500 drop-shadow-[0_0_20px_rgba(244,63,94,0.8)]" : result.ai_probability > 30 ? "text-amber-500 drop-shadow-[0_0_20px_rgba(245,158,11,0.8)]" : "text-cyber-blue drop-shadow-[0_0_20px_rgba(16,185,129,0.8)]"
                )}
              />
            </svg>
            <div className="absolute inset-0 flex flex-col items-center justify-center z-20">
              <motion.span
                initial={{ scale: 0.5, opacity: 0 }}
                animate={{ scale: 1, opacity: 1 }}
                transition={{ duration: 0.8, delay: 1.2, type: "spring" }}
                className="text-6xl font-display font-black text-white leading-none tracking-tighter"
              >
                {Math.round(result.ai_probability)}%
              </motion.span>
              <span className="text-[10px] font-mono text-zinc-500 uppercase tracking-[0.4em] mt-3">AI Match Detected</span>
            </div>
          </div>
        </div>

        {/* Risk & Confidence */}
        <div className="space-y-8">
          <div className={cn(
            "p-10 rounded-none border-l-4 flex flex-col justify-center relative overflow-hidden transition-all duration-500",
            getRiskBg(result.risk_level),
            result.risk_level === "High" ? "border-l-rose-500 glow-pulse-red" : result.risk_level === "Medium" ? "border-l-amber-500" : "border-l-emerald-500",
            getRiskGlow(result.risk_level)
          )}>
            <span className="text-[9px] font-mono uppercase tracking-[0.3em] opacity-40 mb-4">Forensic Threat Level</span>
            <div className="flex items-center gap-5">
              <div className={cn("p-4 rounded-none border border-current bg-white/5", getRiskColor(result.risk_level))}>
                {getRiskIcon(result.risk_level)}
              </div>
              <div>
                <div className={cn("text-4xl font-display font-black uppercase tracking-tighter", getRiskColor(result.risk_level))}>
                  {result.risk_level} Risk
                </div>
                <div className="text-[9px] opacity-40 font-mono uppercase tracking-[0.2em] mt-1">Verification Protocol Complete</div>
              </div>
            </div>
          </div>

          <div className="glass-card rounded-none p-10 flex flex-col justify-center border-t-2 border-t-zinc-800">
            <span className="text-[9px] font-mono uppercase tracking-[0.3em] text-zinc-600 mb-6">Analysis Confidence</span>
            <div className="flex items-end justify-between mb-3">
              <span className="text-3xl font-display font-black text-white uppercase tracking-tighter">{result.confidence}</span>
              <span className="text-[9px] font-mono text-zinc-600 uppercase tracking-widest">Precision Index</span>
            </div>
            <div className="h-1.5 w-full bg-white/5 rounded-none overflow-hidden">
              <motion.div
                initial={{ width: 0 }}
                animate={{ width: result.confidence === "High" ? "95%" : result.confidence === "Medium" ? "65%" : "35%" }}
                className={cn(
                  "h-full transition-all duration-1000",
                  result.confidence === "High" ? "bg-cyber-blue shadow-[0_0_10px_rgba(16,185,129,0.5)]" : result.confidence === "Medium" ? "bg-amber-500" : "bg-zinc-700"
                )}
              />
            </div>
          </div>
        </div>
      </div>

      {/* Analysis Summary */}
      {result.analysis_summary && (
        <div className="glass-card rounded-none p-10 border-l-4 border-l-cyber-blue bg-cyber-blue/5 relative">
          <div className="absolute top-0 right-0 p-4 opacity-10">
            <Activity className="w-12 h-12 text-cyber-blue" />
          </div>
          <h3 className="text-[10px] font-mono uppercase tracking-[0.3em] text-cyber-blue mb-5">Forensic Summary Verdict</h3>
          <p className="text-sm text-zinc-300 leading-relaxed font-mono uppercase tracking-wide">{result.analysis_summary}</p>
        </div>
      )}

      {/* Breakdown Scores */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        {result.frame_artifact_score !== undefined ? (
          <>
            <div className="glass-card rounded-none p-6 flex items-center gap-5 group hover:border-cyber-blue/40 transition-all border-t-2 border-t-cyber-blue/20">
              <div className="w-12 h-12 rounded-none border border-cyber-blue/20 flex items-center justify-center group-hover:bg-cyber-blue/10 transition-colors">
                <Activity className="w-6 h-6 text-cyber-blue" />
              </div>
              <div>
                <div className="text-[9px] uppercase tracking-[0.2em] text-zinc-600 mb-1">Frame Integrity</div>
                <div className="text-xl font-mono font-black text-white">{result.frame_artifact_score}%</div>
              </div>
            </div>
            <div className="glass-card rounded-none p-6 flex items-center gap-5 group hover:border-cyber-blue/40 transition-all border-t-2 border-t-cyber-blue/20">
              <div className="w-12 h-12 rounded-none border border-cyber-blue/20 flex items-center justify-center group-hover:bg-cyber-blue/10 transition-colors">
                <Zap className="w-6 h-6 text-cyber-blue" />
              </div>
              <div>
                <div className="text-[9px] uppercase tracking-[0.2em] text-zinc-600 mb-1">Motion Consistency</div>
                <div className="text-xl font-mono font-black text-white">{result.temporal_score}%</div>
              </div>
            </div>
            <div className="glass-card rounded-none p-6 flex items-center gap-5 group hover:border-emerald-500/40 transition-all border-t-2 border-t-emerald-500/20">
              <div className="w-12 h-12 rounded-none border border-emerald-500/20 flex items-center justify-center group-hover:bg-emerald-500/10 transition-colors">
                <Eye className="w-6 h-6 text-emerald-500" />
              </div>
              <div>
                <div className="text-[9px] uppercase tracking-[0.2em] text-zinc-600 mb-1">Artifact Detection</div>
                <div className="text-xl font-mono font-black text-white">{result.realism_score}%</div>
              </div>
            </div>
          </>
        ) : result.artifact_score !== undefined ? (
          <>
            <div className="glass-card rounded-none p-6 flex items-center gap-5 group hover:border-cyber-blue/40 transition-all border-t-2 border-t-cyber-blue/20">
              <div className="w-12 h-12 rounded-none border border-cyber-blue/20 flex items-center justify-center group-hover:bg-cyber-blue/10 transition-colors">
                <Activity className="w-6 h-6 text-cyber-blue" />
              </div>
              <div>
                <div className="text-[9px] uppercase tracking-[0.2em] text-zinc-600 mb-1">Visual Artifacts</div>
                <div className="text-xl font-mono font-black text-white">{result.artifact_score}%</div>
              </div>
            </div>
            <div className="glass-card rounded-none p-6 flex items-center gap-5 group hover:border-cyber-blue/40 transition-all border-t-2 border-t-cyber-blue/20">
              <div className="w-12 h-12 rounded-none border border-cyber-blue/20 flex items-center justify-center group-hover:bg-cyber-blue/10 transition-colors">
                <Zap className="w-6 h-6 text-cyber-blue" />
              </div>
              <div>
                <div className="text-[9px] uppercase tracking-[0.2em] text-zinc-600 mb-1">Lighting Analysis</div>
                <div className="text-xl font-mono font-black text-white">{result.lighting_score}%</div>
              </div>
            </div>
            <div className="glass-card rounded-none p-6 flex items-center gap-5 group hover:border-emerald-500/40 transition-all border-t-2 border-t-emerald-500/20">
              <div className="w-12 h-12 rounded-none border border-emerald-500/20 flex items-center justify-center group-hover:bg-emerald-500/10 transition-colors">
                <Eye className="w-6 h-6 text-emerald-500" />
              </div>
              <div>
                <div className="text-[9px] uppercase tracking-[0.2em] text-zinc-600 mb-1">Realism Index</div>
                <div className="text-xl font-mono font-black text-white">{result.realism_score}%</div>
              </div>
            </div>
          </>
        ) : (
          <>
            <div className="glass-card rounded-none p-6 flex items-center gap-5 group hover:border-cyber-blue/40 transition-all border-t-2 border-t-cyber-blue/20">
              <div className="w-12 h-12 rounded-none border border-cyber-blue/20 flex items-center justify-center group-hover:bg-cyber-blue/10 transition-colors">
                <Brain className="w-6 h-6 text-cyber-blue" />
              </div>
              <div>
                <div className="text-[9px] uppercase tracking-[0.2em] text-zinc-600 mb-1">Linguistic Naturalness</div>
                <div className="text-xl font-mono font-black text-white">{result.linguistic_score}%</div>
              </div>
            </div>
            <div className="glass-card rounded-none p-6 flex items-center gap-5 group hover:border-cyber-blue/40 transition-all border-t-2 border-t-cyber-blue/20">
              <div className="w-12 h-12 rounded-none border border-cyber-blue/20 flex items-center justify-center group-hover:bg-cyber-blue/10 transition-colors">
                <Layout className="w-6 h-6 text-cyber-blue" />
              </div>
              <div>
                <div className="text-[9px] uppercase tracking-[0.2em] text-zinc-600 mb-1">Structural Pattern</div>
                <div className="text-xl font-mono font-black text-white">{result.structure_score}%</div>
              </div>
            </div>
            <div className="glass-card rounded-none p-6 flex items-center gap-5 group hover:border-emerald-500/40 transition-all border-t-2 border-t-emerald-500/20">
              <div className="w-12 h-12 rounded-none border border-emerald-500/20 flex items-center justify-center group-hover:bg-emerald-500/10 transition-colors">
                <Scale className="w-6 h-6 text-emerald-500" />
              </div>
              <div>
                <div className="text-[9px] uppercase tracking-[0.2em] text-zinc-600 mb-1">Content Genericness</div>
                <div className="text-xl font-mono font-black text-white">{result.genericness_score}%</div>
              </div>
            </div>
          </>
        )}
      </div>

      {/* Expert Panel */}
      {result.expert_panel && (
        <div className="space-y-6">
          <h3 className="text-[10px] font-mono uppercase tracking-[0.4em] text-zinc-600">Forensic Specialist Verdicts</h3>
          <div className="grid grid-cols-1 gap-6">
            {[
              {
                title: result.artifact_score !== undefined ? "Visual Artifact Detector" : "Linguistic Analyst",
                icon: Activity,
                color: "text-cyber-blue",
                verdict: result.expert_panel.artifact_detector
              },
              {
                title: result.artifact_score !== undefined ? "Lighting & Shadow Analyst" : "Pattern Specialist",
                icon: Zap,
                color: "text-cyber-blue",
                verdict: result.expert_panel.lighting_analyst
              },
              {
                title: result.artifact_score !== undefined ? "AI Image Judge" : "AI Forensic Judge",
                icon: ShieldAlert,
                color: "text-cyber-blue",
                verdict: result.expert_panel.ai_judge,
                highlight: true
              }
            ].map((expert, i) => (
              <motion.div
                key={i}
                whileHover={{ y: -4 }}
                className={cn(
                  "glass-card rounded-none p-8 flex gap-8 transition-all duration-300",
                  expert.highlight ? "border-l-4 border-l-cyber-blue bg-cyber-blue/5" : "hover:border-white/10"
                )}
              >
                <div className={cn("w-14 h-14 rounded-none border border-current flex items-center justify-center shrink-0 bg-white/5", expert.color)}>
                  <expert.icon className="w-7 h-7" />
                </div>
                <div>
                  <div className={cn("text-[10px] font-black uppercase tracking-[0.2em] mb-2", expert.color)}>
                    {expert.title}
                  </div>
                  <p className={cn(
                    "text-sm leading-relaxed italic",
                    expert.highlight ? "text-white font-medium not-italic" : "text-zinc-400"
                  )}>
                    "{expert.verdict}"
                  </p>
                </div>
              </motion.div>
            ))}
          </div>
        </div>
      )}

      {/* Forensic Indicators */}
      <div className="glass-card rounded-none p-10 relative overflow-hidden border-t-2 border-t-zinc-800">
        <div className="absolute top-0 right-0 p-8 opacity-5">
          <Fingerprint className="w-32 h-32 text-white" />
        </div>
        <h3 className="text-[10px] font-mono uppercase tracking-[0.4em] text-zinc-600 mb-10 flex items-center gap-4">
          <AlertCircle className="w-4 h-4 text-cyber-blue" />
          Primary Forensic Indicators
        </h3>
        <div className="grid grid-cols-1 gap-8">
          {result.reasons.map((reason, i) => (
            <motion.div
              key={i}
              initial={{ opacity: 0, x: -20 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ delay: i * 0.1 }}
              className="flex items-start gap-5 group"
            >
              <div className="mt-2 w-2 h-2 rounded-none border border-cyber-blue shadow-[0_0_10px_rgba(16,185,129,0.5)] shrink-0" />
              <p className="text-sm text-zinc-400 leading-relaxed group-hover:text-white transition-colors uppercase tracking-wide font-mono">{reason}</p>
            </motion.div>
          ))}
        </div>
      </div>
    </motion.div>
  );
}
